language: node_js
branches:
  only:
    - docs
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
    - "src/node_modules"
before_install:
  - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out travis_rsa -d
  - mv travis_rsa ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  - git config --global user.name okaduki
  - git config --global user.email "okaduki1@gmail.com"
install:
  - npm install
script:
  - npm run build
  - cp README.md docs/
  - cd docs
  - git init
  - git add .
  - git commit -m "Commit by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
  - git push -f git@github.com:okaduki/TAACOPS.git master:master
